name: build-skia
run-name: ${{ github.actor }} is building skia
env:
    TZ: Asia/Shanghai

on: 
  push:
    paths:
      - 'version'

jobs:
  build-skia-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: $ROOT/script/setup_diskspace.sh
      - run: $ROOT/script/fetch_depot.sh
      - run: $ROOT/script/fetch_skia.sh
